openapi: 3.1.0
info:
  title: API сервер для проекта "Шесть городов".
  description: |-
    *Список ресурсов и маршрутов сервера "Шесть городов".
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description: Действия с объявлениями
  - name: comments
    description: Действия с комментариями
  - name: users
    description: Действия с пользователями

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя

      requestBody:
        description: Информация для создания нового пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true

      responses:
        "201":
          description: Пользователь зарегистрированю Объект пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        "409":
          description: Пользователь с таким 'email' уже существует


  /users/ligin:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизирует пользователя на основе логина и пароля

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя.
        Изображение аватара должно быть в формате `png` или `jpg`.

components:
  schemas:
    createUser:
      type: object

      properties:
        email:
          type: string
          example: JohnValyalkin@inbox.ru

        nick:
          type: string
          example: John_Valyalkin

        password:
          type: string
          example: 123456789

        isPro:
          type: boolean
          example: true

    user:
      type: object

      properties:
        id:
          type: string
          example: 734cs798cs9794cd47441ds151pl

        email:
          type: string
          example: JohnValyalkin@inbox.ru
