openapi: 3.1.0
info:
  title: API сервер для проекта "Шесть городов".
  description: |-
    *Список ресурсов и маршрутов сервера "Шесть городов".
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description: Действия с предложениями
  - name: comments
    description: Действия с комментариями
  - name: users
    description: Действия с пользователями

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя

      requestBody:
        description: Информация для создания нового пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true

      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        "409":
          description: Пользователь с таким 'email' уже существует


  /users/ligin:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизирует пользователя на основе логина и пароля

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя.
        Изображение аватара должно быть в формате `png` или `jpg`.


  /offers:
    get:
      tags:
        - offers
      summary: Получить список предложений
      description: Получает список предложений

    post:
      tags:
        - offers
      summary: Создание нового предложения
      description: Создает новое предложение

      requestBody:
        description:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
        required: true


      responses:
        "201":
          description: Предложение создано. Объект предложения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'

        "409":
          description: Ошибка. Предложение не создано


  /offers/{offerId}:
    get:
      tags:
        - offers
      summary: Детальная информация по предложению
      description: Получает детальную информацию по предложению

    put:
      tags:
        - offers
      summary: Редактирование предложения
      description: Редактирует предложение

    delete:
      tags:
        - offers
      summary: Удаление предложения
      description: Удаляет предложение


  /comments/{offerId}:
    get:
      tags:
        - comments
      summary: Получить список комментариев по предложению
      description: Получает список кооментариев по предложению

    post:
      tags:
        - comments
      summary: Добавление комментария по предложению
      description: Добавляет комментарий по предложению


components:
  schemas:
    createUser:
      type: object

      properties:
        email:
          type: string
          example: JohnValyalkin@inbox.ru

        nick:
          type: string
          example: John_Valyalkin

        password:
          type: string
          example: 123456789

        isPro:
          type: boolean
          example: true

    user:
      type: object

      properties:
        id:
          type: string
          example: 734cs798cs9794cd47441ds151pl

        email:
          type: string
          example: JohnValyalkin@inbox.ru

    createOffer:
      type: object

      properties:
        title:
          type: string
          example: Раскошный пентхаус с отдельным входом

        description:
          type: string
          example: Шикарный пентхаус с двумя ярусами

        date:
          type: Date
          example: 2023-02-04T12:05:36.283Z

        city:
          type: string
          example: Amsterdam

        previewImage:
          type: string
          example: pagemini02.jpg

        images:
          type: [string]
          example: [page01.jpg, page02.jpg, page03.jpg, page04.jpg, page05.jpg, page06.jpg]

        isPremium:
          type: boolean
          example: false

        rating:
          type: number
          example: 3

        type:
          type: string
          example: house

        bedrooms:
          type: number
          example: 8

        maxAdults:
          type: number
          example: 9

        price:
          type: number
          example: 534

        goods:
          type: [string]
          example: [Air conditioning, Laptop friendly workspace, Washer, Towels]

        user:
          type: object

          properties:
            email:
              type: string
              example: SaraCo@mail.ru

            nick:
              type: string
              example: Sara Conor

            avatar:
              type: string
              example: avatar01.jpg

            password:
              type: string
              example: 6y7u8i9o

            isPro:
              type: boolean
              example: false

        location:
          type: object

          properties:
            latitude:
              type: number
              example: 48.85669
            longitude:
              type: number
              example: 2.351490


    offer:
      type: object

      properties:
        title:
          type: string
          example: Раскошный пентхаус с отдельным входом

        description:
          type: string
          example: Шикарный пентхаус с двумя ярусами

        date:
          type: Date
          example: 2023-02-04T12:05:36.283Z

        city:
          type: string
          example: Amsterdam

        previewImage:
           type: string
           example: pagemini02.jpg

        images:
          type: [string]
          example: [page01.jpg, page02.jpg, page03.jpg, page04.jpg, page05.jpg, page06.jpg]

        isPremium:
          type: boolean
          example: false

        rating:
          type: number
          example: 3

        type:
          type: string
          example: house

        bedrooms:
          type: number
          example: 8

        maxAdults:
          type: number
          example: 9

        price:
          type: number
          example: 534

        goods:
          type: [string]
          example: [Air conditioning, Laptop friendly workspace, Washer, Towels]

        user:
          type: object

          properties:
            email:
              type: string
              example: SaraCo@mail.ru

            id:
              type: string
              example: 734cs798cs9794cd47441ds151pl

        location:
          type: object

          properties:
            latitude:
              type: number
              example: 48.85669
            longitude:
              type: number
              example: 2.351490

        createdAt:
          type: Date
          example: 2023-06-05T18:41:47.408Z

        updatedAt:
          type: Date
          example: 2023-06-05T18:41:47.408Z
